---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag"
