ansible_become_pass: ENC[AES256_GCM,data:Km5u50nb,iv:b0RLykAzqf62VQdyK5GFMij7L2XK9oiBHDzPSJEIyPs=,tag:3KI3v/cyZqdML8+E8b1mgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZGNYN3lmUlhkbDRJOE9Y
            dmZNWmhzejBnSlpQbzBOaVhWOWEwN1pQZVdjCktuYSs5UFNhQ25jOXlEd0gyM0xM
            WkwwbXkxcUI2ZTU2SldSU1pJbHR1blUKLS0tIHFrdS9JdTRVT1lGMU81ZVhveklw
            UTZac0cvV2NkUExKOWZWUW1MK1VHeHMKwFxqSJS3Hpw4mNCet4l6Lk4VTar+rjLu
            7B2yjS3aQtU6+p+PDJoYuypQS+fI/U6xrXQckzlG6Mv95cyAv9pMTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T02:28:26Z"
    mac: ENC[AES256_GCM,data:JibGGRnqSLVTWqSqSTqG2qa0B1iBElbchm42V0YH4OrUvLYV7UdqBeMFo4uehX/atq3YTFa5b4lRkCzGurAjD/veAs3wfGeCqWAQx6TeB9snhHnT5kVNoEPu1gRtqdCD29XAR1to/XMVgZ9ZysPsLbqRkvcTeiBI1EGqwWvioh0=,iv:VRDp2qa8bwaVO/tAt6Hn2CbXY+b3+V+IMhgdJHIwkgg=,tag:/Kf2CS6HTHqK06KOyO0CPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
