apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:f7GNGJ5aGHG/qdQQ+sDAzc6BRM8S4isH,iv:XWkFMso9kRjJ9s5aFzRCwxECz2J8O77x3VM5jyJx4+k=,tag:3FkHgbGHFbGfSNbRE4v+pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTEZ4b2hUQ0ZEb1FhSDRs
            SUY2NmM4dEVMMmdyOTltQVdEK1Zac1NyUkFzCjhldlJUNUYvUlEzaU5xNEw3WVFW
            V0RndHRrR2xVeXJhSHlhNFREM2xNcjAKLS0tIGVHcGFqdG1aUGNNcEdlVUE4MGJS
            T1ZPeCtmMkt0UnJXdXIxSlh2VTAxa1UKnm1HgZvGxNs7kWt7UBY/7XgAwCdscNS7
            51oA9JMmd/a5y55xejHT3oK7JlWjhMey+O1VobLx0BBaZW6QstaWPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T02:29:02Z"
    mac: ENC[AES256_GCM,data:Lm2WsPsckakjhxAXyiYjiXaLfPMZvBUvUckJVl3yb8dYwU8KOD7Ft4ylwB47qumyD2J3C4ZOcVbVfqaYf42T9lel07upZpCFxVkuXP4KWtnWjjIJUD9uN0mUurgFYCPR+Zdf2Tp8azh54eHyLlR7IuuabFe6RpxfiAvA/TnS9Do=,iv:HN/SQO8vG6BplisLC0DJsBlULcBBySlBHr8+zF9cK8U=,tag:amQqpYiBkcArqqQa+F7c0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
