apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:eOPOr2znIE/i+oRMFgQB/Dg1izC7t36d13ONf15yvoGSBzrAG1RuLg==,iv:QHeo5tcBZePdTPCQh2U2YIE+1dEL3T2TMsA5WXPIE6I=,tag:n+g+vKkFYDxmhjDMHS1tYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q1NUMzlodGlGV0RKeDF3
            NjQyNzlpOU1rLzdtTjh6SWxxeXJvVkFiNTJVCmFlRHkvU25wcHZJaUdUQ0VpQ3M0
            SWVicTZMTFUzSURtVHByYkdXSmRURTQKLS0tIGQ2Z0ZYN2lYY3AwdVJja2Z6RVhy
            V3ljVVlyNTc2N0lVOStVYzc5WTcrUW8KJG+it9QQr8p9g6z0gbZjdJZsnaNbzJmB
            7svU6Mmpt1yFMXMp0Xvnx2u6H2UXYF+VkckgGwHceTDo+c30Gu9+/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T02:29:03Z"
    mac: ENC[AES256_GCM,data:hvpEzVUt011d8KZfZfSVnDWJZYiijl86HOo7MGKqKvqHiPdCMxMEQ9SPDGSdVwqRga5qC18tyRNtbFcJq14CBvH7wDIT+MHYgqwt3DLii2uoG0cxsyU2hLnH3eskytP4Al5vvQctprGWAUAEeViGtEqK9421CxeaejOiT5kCsyo=,iv:VhQpcASgDVjL6CYAvxLvekamyGoiDwm7cmK3gTRx1m8=,tag:jREaMw4uX4UJR6CTI69PIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
