---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: docker

spec:
  interval: 30m
  chart:
    spec:
      chart: docker-registry
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system

  maxHistory: 2

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    image:
      repository: twuni/docker-registry
      tag: 2.7.1
      pullPolicy: IfNotPresent

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "docker-registry.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    
    persistence:
      data:
        enabled: true
        existingClaim: docker-registry-pvc
        mountPath: /docker-registry