apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eV57pE0joH8963yTPGpfmmPkRVSOpxGEig==,iv:wXecSSKlvuXux3rU53f18Pd1mlJTr2pQD6ELARLVSHc=,tag:JHKzeiE9cBvbI1/8jdXAhA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BZUnQkFmZUM1w5Q21I8nqRj9ggX/AegVXmnamPqDLp3HwauV,iv:+Tq8+mu7a8+oK417EWSK0WkZpSQorkVZHjPVeC5RHNQ=,tag:BHqwm79Asl4pwTEOvfWt4w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:h31ZSsGXTgKKYI6eCcbnUF4SJw==,iv:+w+F+oih4y/T9j2VwbZxdqIyRmNPkvcRYB+36zuyFX8=,tag:pWs5vWvozuYCnMu/hCHxYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mkdtrdzs03p8kldlelllns56kpch766lgj5qcsqpw4puxpt4gasu6lmag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYkphT3pPOUQ1bzRGN1Y4
            b3Y3MHJiZENETS82RWFnbDF0VkZ3NEt5TVd3CmtnZDBTcG16SmFwZkJBTEx2ZzZH
            VkJBY3JVSVJFTjZGOXA1WC81aHN6QzQKLS0tIHptZFhZSlJvSCtvZ2dPSFY5VThQ
            VUpDTkpHaEhpcHNXMWd6SGNXT3R1OUEKPj46GVVhhu168sFXatv0qtx95cupX6hX
            lE7XVO1/n5/cYZdeuFBguUHj725e1atq7Ur3EnqRkUrO70w9ggR/WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T02:29:03Z"
    mac: ENC[AES256_GCM,data:KrNHX7tF3leRmv4mx+bVHnIirZ8Rd6UXe/Wrm66zwGMU+c5kl+8mOzFRdakCFKyDqY/oZoqyl3ZNw7iPZFh0Fn8g1O11JKR7S/eZBN9rbV52k+Bz15UHTEliCwN4P0B6RR1+9Xmhfb7KibqRSpCJgg3S2U0hmfH6bpKyUyZit5A=,iv:Yt+eKZwm6r1I3TjNuobKMaB7vNkmpAz8FEu5gwb3qNo=,tag:6KPdRJjcphdLF1BT5kYIRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
