
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: octoprint
      version: 6.3.1
      sourceRef:
        kind: HelmRepository
        name: octoprint
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    octoprint:
      nodeselctor:
        rpi: rpi3b
        3dprinter: true
      namespaceSelector:
        matchNames:
          - default
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "octoprint.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        annotations:
          hajimari.io/icon: mdi:printer-3d
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
