---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: default

spec:
  interval: 5m
  chart:
    spec:
      chart: octoprint
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: octoprint/octoprint
      tag: 1.9.3
      pullPolicy: IfNotPresent

    nodeSelector:
      rpi: rpi3b
      3dprinter: yes
    
    tolerations:
    - key: "lowresarm"
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"
    
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 200Mi

    env:
      TZ: 'America/Los_Angeles'
      OCTOPRINT_PORT: 5000
    
    securityContext:
      # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
      privileged: true
    
    persistence:
      data:
        enabled: true
        existingClaim: octoprint-data
        mountPath: /octoprint
      printer:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Prusa_Research__prusa3d.com__Original_Prusa_i3_MK3_CZPX0321X004XK45917-if00
        mountPath: /dev/ttyUSB0

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "octoprint.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        annotations:
          hajimari.io/icon: mdi:printer-3d
