---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: octoprint
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nodeselctor:
      rpi: rpi3b
      3dprinter: true
    namespaceSelector:
      matchNames:
        - default
    image:
      repository: octoprint/octoprint
      tag: 1.7.3
      pullPolicy: IfNotPresent

    env:
      TZ: 'America/Lost_Angeles'
      OCTOPRINT_PORT: 5000
    
    persistence:
      data:
        enabled: true
        existingClaim: octoprint-data
        mountPath: /octoprint
      printer:
        enabled: false
        type: hostPath
        hostPath: /dev/ttyUSB0

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "octoprint.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        annotations:
          hajimari.io/icon: mdi:printer-3d
